spring:
  application:
    name: endless-odyssey

  datasource:
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: ${SUPABASE_USERNAME}
    password: ${SUPABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health"
