name: Docker Build and Test for Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080
          - 3000:3000

    env:
      SUPABASE_USERNAME: ${{ secrets.SUPABASE_USERNAME }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build backend Docker container using Dockerfile in backend folder
      - name: Build Docker image for backend
        run: |
          cd backend && docker build -t backend-image .

      # Run the Docker container in detached mode for testing
      - name: Run Docker container for backend
        run: |
          docker run -d --name backend-container -p 8080:8080 -p 3000:3000 backend-image
          
      # Optionally, stop and clean up containers after the test
      - name: Stop and clean up containers
        run: |
          docker stop backend-container
          docker rm backend-container
